Feature server chatgpt test
itsp-pbl-2023/tonkatsu pull request #38
Opened 2023-06-20 08:23 UTC by ShimboAkito

2023-06-23 09:55 UTC, SgKnt requested changes

2023-06-23 09:55 UTC, SgKnt commented on server/internal/routers/router.go
> +	r.POST("/chatgpt", api.ChatGPT)
`r.POST("/chatgpt", api.Session, api.ChatGPT)`がいいかも

2023-06-25 08:15 UTC, ShimboAkito commented on server/internal/routers/router.go
> +	r.POST("/chatgpt", api.ChatGPT)
修正しました。

2023-06-26 07:37 UTC, SgKnt approved these changes

2023-06-27 05:09 UTC, merged